-- MySQL Script generated by MySQL Workbench
-- Min 07 Peb 2016 04:19:14  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema siem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `role_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `user_full_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `user_password` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `user_email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `user_image` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `user_description` TEXT NULL DEFAULT NULL COMMENT '',
  `user_role_role_id` INT(11) NULL COMMENT '',
  `user_is_deleted` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `user_input_date` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `user_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  INDEX `fk_user_user_role1_idx` (`user_role_role_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_role_id`)
    REFERENCES `user_role` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `activity_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `activity_log` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `log_date` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `log_action` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `log_module` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `log_info` TEXT NULL DEFAULT NULL COMMENT '',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`log_id`)  COMMENT '',
  INDEX `fk_g_activity_log_g_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_g_activity_log_g_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` VARCHAR(40) NOT NULL COMMENT '',
  `ip_address` VARCHAR(45) NOT NULL COMMENT '',
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `data` BLOB NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ci_sessions_timestamp` (`timestamp` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mediamanager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamanager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `isfile` TINYINT(1) NULL DEFAULT '0' COMMENT '',
  `label` TEXT NULL DEFAULT NULL COMMENT '',
  `info` TEXT NULL DEFAULT NULL COMMENT '',
  `upload_at` DATETIME NULL DEFAULT NULL COMMENT '',
  `album_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `mediamanager_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamanager_album` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `label` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `upload_at` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `posts_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `category_name` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`category_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts` (
  `posts_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `posts_title` VARCHAR(255) NULL COMMENT '',
  `posts_description` TEXT NULL COMMENT '',
  `posts_image` VARCHAR(255) NULL COMMENT '',
  `posts_published_date` TIMESTAMP NULL COMMENT '',
  `posts_is_published` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `posts_category_category_id` INT NULL COMMENT '',
  `user_user_id` INT(11) NULL COMMENT '',
  `posts_input_date` TIMESTAMP NULL COMMENT '',
  `posts_last_update` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`posts_id`)  COMMENT '',
  INDEX `fk_posts_posts_category1_idx` (`posts_category_category_id` ASC)  COMMENT '',
  INDEX `fk_posts_user1_idx` (`user_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_posts_posts_category1`
    FOREIGN KEY (`posts_category_category_id`)
    REFERENCES `posts_category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_posts_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employe` (
  `employe_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `employe_nik` VARCHAR(100) NOT NULL COMMENT '',
  `employe_name` VARCHAR(255) NULL COMMENT '',
  `employe_phone` VARCHAR(45) NULL COMMENT '',
  `employe_address` TEXT NULL COMMENT '',
  `employe_divisi` VARCHAR(255) NULL COMMENT '',
  `employe_position` VARCHAR(100) NULL COMMENT '',
  `employe_departement` VARCHAR(255) NULL COMMENT '',
  `employe_is_active` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `employe_date_register` DATE NULL COMMENT '',
  `employe_input_date` TIMESTAMP NULL COMMENT '',
  `employe_last_update` TIMESTAMP NULL COMMENT '',
  `user_user_id` INT NULL COMMENT '',
  PRIMARY KEY (`employe_id`, `employe_nik`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memorandum1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorandum1` (
  `memorandum_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `memorandum_number` VARCHAR(45) NULL COMMENT '',
  `memorandum_email_date` DATE NULL COMMENT '',
  `memorandum_absent_date` DATE NULL COMMENT '',
  `memorandum_date_sent` DATE NULL COMMENT '',
  `memorandum_call_date` DATE NULL COMMENT '',
  `user_user_id` INT NULL COMMENT '',
  `memorandum_is_present` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `memorandum_finished_desc` TEXT NULL COMMENT '',
  `memorandum_input_date` TIMESTAMP NULL COMMENT '',
  `memorandum_last_update` TIMESTAMP NULL COMMENT '',
  `employe_employe_nik` INT NULL COMMENT '',
  PRIMARY KEY (`memorandum_id`)  COMMENT '',
  INDEX `fk_memorandum1_employe1_idx` (`employe_employe_nik` ASC)  COMMENT '',
  CONSTRAINT `fk_memorandum1_employe1`
    FOREIGN KEY (`employe_employe_nik`)
    REFERENCES `employe` (`employe_nik`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memorandum2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorandum2` (
  `memorandum_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `memorandum_number` VARCHAR(45) NULL COMMENT '',
  `memorandum_date_sent` DATE NULL COMMENT '',
  `memorandum_call_date` DATE NULL COMMENT '',
  `memorandum1_memorandum_id` INT NULL COMMENT '',
  `user_user_id` INT NULL COMMENT '',
  `memorandum_is_present` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `memorandum_input_date` TIMESTAMP NULL COMMENT '',
  `memorandum_last_update` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`memorandum_id`)  COMMENT '',
  INDEX `fk_memorandum2_memorandum11_idx` (`memorandum1_memorandum_id` ASC)  COMMENT '',
  CONSTRAINT `fk_memorandum2_memorandum11`
    FOREIGN KEY (`memorandum1_memorandum_id`)
    REFERENCES `memorandum1` (`memorandum_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memorandum3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorandum3` (
  `memorandum_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `memorandum_number` VARCHAR(45) NULL COMMENT '',
  `memorandum_date_sent` DATE NULL COMMENT '',
  `memorandum_call_date` DATE NULL COMMENT '',
  `memorandum2_memorandum_id` INT NULL COMMENT '',
  `user_user_id` INT NULL COMMENT '',
  `memorandum_is_present` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `memorandum_input_date` TIMESTAMP NULL COMMENT '',
  `memorandum_last_update` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`memorandum_id`)  COMMENT '',
  INDEX `fk_memorandum2_memorandum21_idx` (`memorandum2_memorandum_id` ASC)  COMMENT '',
  CONSTRAINT `fk_memorandum2_memorandum21`
    FOREIGN KEY (`memorandum2_memorandum_id`)
    REFERENCES `memorandum2` (`memorandum_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank` (
  `bank_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `bank_name` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`bank_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spb` (
  `spb_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `spb_number` VARCHAR(45) NULL COMMENT '',
  `spb_date` DATE NULL COMMENT '',
  `bank_bank_id` INT NULL COMMENT '',
  `user_user_id` INT NULL COMMENT '',
  `spb_name1` VARCHAR(255) NULL COMMENT '',
  `spb_nik1` VARCHAR(16) NULL COMMENT '',
  `spb_name2` VARCHAR(255) NULL COMMENT '',
  `spb_nik2` VARCHAR(16) NULL COMMENT '',
  `spb_name3` VARCHAR(255) NULL COMMENT '',
  `spb_nik3` VARCHAR(16) NULL COMMENT '',
  `spb_name4` VARCHAR(255) NULL COMMENT '',
  `spb_nik4` VARCHAR(16) NULL COMMENT '',
  `spb_name5` VARCHAR(255) NULL COMMENT '',
  `spb_nik5` VARCHAR(16) NULL COMMENT '',
  `spb_name6` VARCHAR(255) NULL COMMENT '',
  `spb_nik6` VARCHAR(16) NULL COMMENT '',
  `spb_name7` VARCHAR(255) NULL COMMENT '',
  `spb_nik7` VARCHAR(16) NULL COMMENT '',
  `spb_name8` VARCHAR(255) NULL COMMENT '',
  `spb_nik8` VARCHAR(16) NULL COMMENT '',
  `spb_name9` VARCHAR(255) NULL COMMENT '',
  `spb_nik9` VARCHAR(16) NULL COMMENT '',
  `spb_name10` VARCHAR(255) NULL COMMENT '',
  `spb_nik10` VARCHAR(16) NULL COMMENT '',
  `spb_input_date` TIMESTAMP NULL COMMENT '',
  `spb_last_update` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`spb_id`)  COMMENT '',
  INDEX `fk_spb_bank1_idx` (`bank_bank_id` ASC)  COMMENT '',
  CONSTRAINT `fk_spb_bank1`
    FOREIGN KEY (`bank_bank_id`)
    REFERENCES `bank` (`bank_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sk` (
  `sk_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sk_number` VARCHAR(45) NULL COMMENT '',
  `sk_description` TEXT NULL COMMENT '',
  `sk_date` DATE NULL COMMENT '',
  `user_user_id` INT NULL COMMENT '',
  `sk_input_date` TIMESTAMP NULL COMMENT '',
  `sk_last_update` TIMESTAMP NULL COMMENT '',
  `employe_employe_nik` INT NULL COMMENT '',
  PRIMARY KEY (`sk_id`)  COMMENT '',
  INDEX `fk_sk_employe1_idx` (`employe_employe_nik` ASC)  COMMENT '',
  CONSTRAINT `fk_sk_employe1`
    FOREIGN KEY (`employe_employe_nik`)
    REFERENCES `employe` (`employe_nik`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contract` (
  `contract_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `contract_number` VARCHAR(45) NULL COMMENT '',
  `contract_ke` DECIMAL(10,0) NULL COMMENT '',
  `contract_date` DATE NULL COMMENT '',
  `user_user_id` INT NULL COMMENT '',
  `contract_input_date` TIMESTAMP NULL COMMENT '',
  `contract_last_update` TIMESTAMP NULL COMMENT '',
  `employe_employe_nik` INT NULL COMMENT '',
  PRIMARY KEY (`contract_id`)  COMMENT '',
  INDEX `fk_contract_employe1_idx` (`employe_employe_nik` ASC)  COMMENT '',
  CONSTRAINT `fk_contract_employe1`
    FOREIGN KEY (`employe_employe_nik`)
    REFERENCES `employe` (`employe_nik`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stl` (
  `stl_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `stl_number` VARCHAR(45) NULL COMMENT '',
  `stl_date` DATE NULL COMMENT '',
  `stl_batch` DECIMAL(10,0) NULL COMMENT '',
  `stl_ipk` VARCHAR(45) NULL COMMENT '',
  `stl_desc` VARCHAR(45) NULL COMMENT '',
  `user_user_id` INT NULL COMMENT '',
  `stl_input_date` TIMESTAMP NULL COMMENT '',
  `stl_last_update` TIMESTAMP NULL COMMENT '',
  `employe_employe_nik` INT NULL COMMENT '',
  PRIMARY KEY (`stl_id`)  COMMENT '',
  INDEX `fk_stl_employe1_idx` (`employe_employe_nik` ASC)  COMMENT '',
  CONSTRAINT `fk_stl_employe1`
    FOREIGN KEY (`employe_employe_nik`)
    REFERENCES `employe` (`employe_nik`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
